name: default-actions
on:
  push:
    branches:
      - develop

jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Dependencies
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyinstaller
          pyinstaller build.spec
          python ./tools/ci_notify.py
